# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"\x07\n\x05\x45mpty\"4\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\"\n\rAddStatusTodo\x12\x11\n\tcompleted\x18\x01 \x01(\x08\"-\n\x10TodoListResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"2\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"%\n\x12UpdateTodoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb9\x01\n\x0bTodoService\x12\x32\n\x0bGetTodoList\x12\x0b.todo.Empty\x1a\x16.todo.TodoListResponse\x12\x45\n\x10UpdateTodoStatus\x12\x17.todo.UpdateTodoRequest\x1a\x18.todo.UpdateTodoResponse\x12/\n\x0c\x41\x64\x64TodoEntry\x12\n.todo.Todo\x1a\x13.todo.AddStatusTodob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_TODO']._serialized_start=29
  _globals['_TODO']._serialized_end=81
  _globals['_ADDSTATUSTODO']._serialized_start=83
  _globals['_ADDSTATUSTODO']._serialized_end=117
  _globals['_TODOLISTRESPONSE']._serialized_start=119
  _globals['_TODOLISTRESPONSE']._serialized_end=164
  _globals['_UPDATETODOREQUEST']._serialized_start=166
  _globals['_UPDATETODOREQUEST']._serialized_end=216
  _globals['_UPDATETODORESPONSE']._serialized_start=218
  _globals['_UPDATETODORESPONSE']._serialized_end=255
  _globals['_TODOSERVICE']._serialized_start=258
  _globals['_TODOSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
